name: uang_qas
description: Aplikasi Manajemen Kas Kelas Offline - by Umar Ulkhak
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.19.0
  shared_preferences: ^2.1.0
  crypto: ^3.0.2
  csv: ^5.0.0
  path: ^1.9.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Diperbarui ke ^6.0.0 dan dipastikan hanya ada di dev_dependencies
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
